### ISSUE TITLE
Would you please share a guide code to execute for your label removed GAN?

### ISSUE THREAD

**Issue by ahnsony** [zhaoxin94/awesome-gan#1]
Hello, Zhao
Nice e-meet you. I got an good inspiration from your label removed GAN, actually for now I would like to make a model using conditional GAN, but as you mentioned in your article which is very burdensome work, so I would like to adopt your idea when I make a model regarding GAN based augmentation.
Would you please share your guide code (working code) so that I could run with?

Best regards,
Ahnsony

**Comment by zhaoxin94** [comment]
Hi Ahnsony,

Sorry, "label removed GAN" is not my work. So, I'm afraid I cannot provide you the code.

Best regards,
Xin Zhao
________________________________
发件人: ahnsony <notifications@github.com>
发送时间: 2020年3月26日 0:25
收件人: zhaoxin94/awesome-gan <awesome-gan@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zhaoxin94/awesome-gan] Would you please share a guide code to execute for your label removed GAN? (#1)


Hello, Zhao
Nice e-meet you. I got an good inspiration from your label removed GAN, actually for now I would like to make a model using conditional GAN, but as you mentioned in your article which is very burdensome work, so I would like to adopt your idea when I make a model regarding GAN based augmentation.
Would you please share your guide code (working code) so that I could run with?

Best regards,
Ahnsony

―

**Comment by ahnsony** [comment]
Hi, Zhao.
Thank you for answering me, would you please let me know who is in charge of this code or project? It would be very helpful for us to develop & enhance your team's project's results which we could contribute on your project's achievement as well.
Br,
Ahnsony

**Comment by zhaoxin94** [comment]
Sorry, I don't know who is in charge of this project.
